### ISSUE TITLE
Control + "\" -- do not work by default

### ISSUE THREAD

**Issue by ucomru** [alexghergh/nvim-tmux-navigation#20]
Good day!

I use with:
- TMUX -- `set -g @plugin 'christoomey/vim-tmux-navigator'`
- VIM -- `Plug 'christoomey/vim-tmux-navigator'`
- NVIM -- `Lasy: "alexghergh/nvim-tmux-navigation"`

CTRL + [h,j,k,l] work well, 
but "CTRL + \" do not work with **`"alexghergh/nvim-tmux-navigation"`**
by default (with out custom mapping)
do not workin not with Tmux, not with out tmux [zsh only]

**Comment by alexghergh** [comment]
Hello!

Could you please give more information? I unfortunately am unable to reproduce the issue.

Perhaps the problem could be collision with another binding in Neovim. Please disable all other plugins and see if the issue persists. Additionally, if this doesn't solve your issue, please post your tmux and neovim configs.

**Comment by ucomru** [comment]
Good day! 
Im using LunarNvim
I think the problem with it...
Its do not work with 'christoomey/vim-tmux-navigator' and "alexghergh/nvim-tmux-navigation".

**Comment by alexghergh** [comment]
I see! Well, I'm fairly confident that LunarNvim might have conflicts with the plugin, since, as far as I know, it maps some things by default. Unfortunately, if this is the case, you have to manually remap whatever LunarNvim is mapping `Ctrl + \` to, and then use `alexghergh/nvim-tmux-navigation` normally.

If you need further assistance with the issue please post your neovim and tmux config files.

Have a great day!

**Comment by ucomru** [comment]
You're right!!
Thanks
