### ISSUE TITLE
Plugin works via the command line but not the keybinding 

### ISSUE THREAD

**Issue by AxZxP** [alexghergh/nvim-tmux-navigation#6]
I'm using Alacritty / Fish / Tmux 3.3a / Nvim 0.7 on macOS 10.15.7

I can't manage to make this plugin work. If I insert `:lua require'nvim-tmux-navigation'.NvimTmuxNavigateLeft()` in the Nvim command it works fine but the keybinding is not responding. I made a gist of my relevant config files below : 

Here is my plugin file : https://gist.github.com/AxZxP/660f21651674599432a7e4b1e2976a30

keymap : https://gist.github.com/AxZxP/2b90e9dcb67bacc53fdaebbcd75ffbab

tmux conf : https://gist.github.com/AxZxP/cadd70ea99a9de01140d1152c2f76f14

**Comment by alexghergh** [comment]
Hey, thanks for submitting a bug report!

I will take a look at it the following days.

Off the top of my mind, some issues might arise in different environments like tmux3.3a, fish, alacritty etc. Some of these programs might capture the keybinds before they reach the neovim plugin. I believe the issue is not with the code itself, as I myself and many others seem to use it without problems, however I don't exclude that possibility.

Are you able to test an older version of tmux, bash/zsh, an older version of neovim until I can take a look?

**Comment by AxZxP** [comment]
Hey Alex, the plugin works now. It's very strange, I made sure to source every config multiple times. You can close the issue if you want, the plugin is SMOOTH with no lag between a vim or tmux pan.

**Comment by alexghergh** [comment]
All good! Let me know if something else happens in the meantime and we can reopen this!
